add_test([=[CalculatorTest.AddPositive]=]  /home/test182/calculator/build_debug/tests [==[--gtest_filter=CalculatorTest.AddPositive]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CalculatorTest.AddPositive]=]  PROPERTIES WORKING_DIRECTORY /home/test182/calculator/build_debug SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CalculatorTest.AddNegative]=]  /home/test182/calculator/build_debug/tests [==[--gtest_filter=CalculatorTest.AddNegative]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CalculatorTest.AddNegative]=]  PROPERTIES WORKING_DIRECTORY /home/test182/calculator/build_debug SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CalculatorTest.AddOverflowCheck]=]  /home/test182/calculator/build_debug/tests [==[--gtest_filter=CalculatorTest.AddOverflowCheck]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CalculatorTest.AddOverflowCheck]=]  PROPERTIES WORKING_DIRECTORY /home/test182/calculator/build_debug SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CalculatorTest.SubtractPositive]=]  /home/test182/calculator/build_debug/tests [==[--gtest_filter=CalculatorTest.SubtractPositive]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CalculatorTest.SubtractPositive]=]  PROPERTIES WORKING_DIRECTORY /home/test182/calculator/build_debug SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CalculatorTest.SubtractNegative]=]  /home/test182/calculator/build_debug/tests [==[--gtest_filter=CalculatorTest.SubtractNegative]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CalculatorTest.SubtractNegative]=]  PROPERTIES WORKING_DIRECTORY /home/test182/calculator/build_debug SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CalculatorTest.SubtractOverflowCheckMax]=]  /home/test182/calculator/build_debug/tests [==[--gtest_filter=CalculatorTest.SubtractOverflowCheckMax]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CalculatorTest.SubtractOverflowCheckMax]=]  PROPERTIES WORKING_DIRECTORY /home/test182/calculator/build_debug SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CalculatorTest.SubtractOverflowCheckMin]=]  /home/test182/calculator/build_debug/tests [==[--gtest_filter=CalculatorTest.SubtractOverflowCheckMin]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CalculatorTest.SubtractOverflowCheckMin]=]  PROPERTIES WORKING_DIRECTORY /home/test182/calculator/build_debug SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CalculatorTest.MultiplyPositive]=]  /home/test182/calculator/build_debug/tests [==[--gtest_filter=CalculatorTest.MultiplyPositive]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CalculatorTest.MultiplyPositive]=]  PROPERTIES WORKING_DIRECTORY /home/test182/calculator/build_debug SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CalculatorTest.MultiplyNegative]=]  /home/test182/calculator/build_debug/tests [==[--gtest_filter=CalculatorTest.MultiplyNegative]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CalculatorTest.MultiplyNegative]=]  PROPERTIES WORKING_DIRECTORY /home/test182/calculator/build_debug SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CalculatorTest.MultiplyOverflowCheckMax]=]  /home/test182/calculator/build_debug/tests [==[--gtest_filter=CalculatorTest.MultiplyOverflowCheckMax]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CalculatorTest.MultiplyOverflowCheckMax]=]  PROPERTIES WORKING_DIRECTORY /home/test182/calculator/build_debug SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CalculatorTest.DividePositive]=]  /home/test182/calculator/build_debug/tests [==[--gtest_filter=CalculatorTest.DividePositive]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CalculatorTest.DividePositive]=]  PROPERTIES WORKING_DIRECTORY /home/test182/calculator/build_debug SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CalculatorTest.DivideNegative]=]  /home/test182/calculator/build_debug/tests [==[--gtest_filter=CalculatorTest.DivideNegative]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CalculatorTest.DivideNegative]=]  PROPERTIES WORKING_DIRECTORY /home/test182/calculator/build_debug SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CalculatorTest.DivideZero]=]  /home/test182/calculator/build_debug/tests [==[--gtest_filter=CalculatorTest.DivideZero]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CalculatorTest.DivideZero]=]  PROPERTIES WORKING_DIRECTORY /home/test182/calculator/build_debug SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CalculatorTest.DivideOverflowCheckMax]=]  /home/test182/calculator/build_debug/tests [==[--gtest_filter=CalculatorTest.DivideOverflowCheckMax]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CalculatorTest.DivideOverflowCheckMax]=]  PROPERTIES WORKING_DIRECTORY /home/test182/calculator/build_debug SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CalculatorTest.ExponentiationOverflowCheck]=]  /home/test182/calculator/build_debug/tests [==[--gtest_filter=CalculatorTest.ExponentiationOverflowCheck]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CalculatorTest.ExponentiationOverflowCheck]=]  PROPERTIES WORKING_DIRECTORY /home/test182/calculator/build_debug SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CalculatorTest.NegativeExponentiation]=]  /home/test182/calculator/build_debug/tests [==[--gtest_filter=CalculatorTest.NegativeExponentiation]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CalculatorTest.NegativeExponentiation]=]  PROPERTIES WORKING_DIRECTORY /home/test182/calculator/build_debug SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CalculatorTest.ZeroBaseAndZeroExp]=]  /home/test182/calculator/build_debug/tests [==[--gtest_filter=CalculatorTest.ZeroBaseAndZeroExp]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CalculatorTest.ZeroBaseAndZeroExp]=]  PROPERTIES WORKING_DIRECTORY /home/test182/calculator/build_debug SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CalculatorTest.ZeroBase]=]  /home/test182/calculator/build_debug/tests [==[--gtest_filter=CalculatorTest.ZeroBase]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CalculatorTest.ZeroBase]=]  PROPERTIES WORKING_DIRECTORY /home/test182/calculator/build_debug SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CalculatorTest.PositiveBaseExponentiation]=]  /home/test182/calculator/build_debug/tests [==[--gtest_filter=CalculatorTest.PositiveBaseExponentiation]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CalculatorTest.PositiveBaseExponentiation]=]  PROPERTIES WORKING_DIRECTORY /home/test182/calculator/build_debug SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CalculatorTest.NegativeBaseExponentiation]=]  /home/test182/calculator/build_debug/tests [==[--gtest_filter=CalculatorTest.NegativeBaseExponentiation]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CalculatorTest.NegativeBaseExponentiation]=]  PROPERTIES WORKING_DIRECTORY /home/test182/calculator/build_debug SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CalculatorTest.Factorial]=]  /home/test182/calculator/build_debug/tests [==[--gtest_filter=CalculatorTest.Factorial]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CalculatorTest.Factorial]=]  PROPERTIES WORKING_DIRECTORY /home/test182/calculator/build_debug SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CalculatorTest.FactorialOne]=]  /home/test182/calculator/build_debug/tests [==[--gtest_filter=CalculatorTest.FactorialOne]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CalculatorTest.FactorialOne]=]  PROPERTIES WORKING_DIRECTORY /home/test182/calculator/build_debug SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CalculatorTest.FactorialZero]=]  /home/test182/calculator/build_debug/tests [==[--gtest_filter=CalculatorTest.FactorialZero]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CalculatorTest.FactorialZero]=]  PROPERTIES WORKING_DIRECTORY /home/test182/calculator/build_debug SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CalculatorTest.NegativeBaseFactorial]=]  /home/test182/calculator/build_debug/tests [==[--gtest_filter=CalculatorTest.NegativeBaseFactorial]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CalculatorTest.NegativeBaseFactorial]=]  PROPERTIES WORKING_DIRECTORY /home/test182/calculator/build_debug SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CalculatorTest.FactorialOverflow]=]  /home/test182/calculator/build_debug/tests [==[--gtest_filter=CalculatorTest.FactorialOverflow]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CalculatorTest.FactorialOverflow]=]  PROPERTIES WORKING_DIRECTORY /home/test182/calculator/build_debug SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  tests_TESTS CalculatorTest.AddPositive CalculatorTest.AddNegative CalculatorTest.AddOverflowCheck CalculatorTest.SubtractPositive CalculatorTest.SubtractNegative CalculatorTest.SubtractOverflowCheckMax CalculatorTest.SubtractOverflowCheckMin CalculatorTest.MultiplyPositive CalculatorTest.MultiplyNegative CalculatorTest.MultiplyOverflowCheckMax CalculatorTest.DividePositive CalculatorTest.DivideNegative CalculatorTest.DivideZero CalculatorTest.DivideOverflowCheckMax CalculatorTest.ExponentiationOverflowCheck CalculatorTest.NegativeExponentiation CalculatorTest.ZeroBaseAndZeroExp CalculatorTest.ZeroBase CalculatorTest.PositiveBaseExponentiation CalculatorTest.NegativeBaseExponentiation CalculatorTest.Factorial CalculatorTest.FactorialOne CalculatorTest.FactorialZero CalculatorTest.NegativeBaseFactorial CalculatorTest.FactorialOverflow)
